# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd0170d31baa10a8ad5265e1cf05d4b5"
name = "LSP hakaton app"
application_url = "https://lcp-hakatom.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "themes/publish", "themes/update" ]
  uri = "/webhooks/themes"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "collections/create", "collections/update", "collections/delete" ]
  uri = "/webhooks/collections"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated" ]
  uri = "/webhooks/orders"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_channels,read_checkouts,read_content,read_customers,read_draft_orders,read_inventory,read_inventory_transfers,read_online_store_pages,read_order_edits,read_orders,read_product_feeds,read_product_listings,read_products,read_purchase_options,read_reports,read_themes"

[auth]
redirect_urls = [
  "https://lcp-hakatom.vercel.app/auth/callback",
  "https://lcp-hakatom.vercel.app/auth/shopify/callback",
  "https://lcp-hakatom.vercel.app/api/auth/callback",
  "https://lcp-hakatom.vercel.app/api/auth"
]
